news_list:
    path: '/api/news'
    controller: App\Controller\NewsController::getNews
    methods: ['GET']

new_detail:
    path: /api/news/{id}
    controller: App\Controller\Api\NewsController::getNewDetail
    methods: [GET]

api_platform:
    resource: .
    type: api_platform
    prefix: /api
