controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_news:
    path: /news/add-news
    controller: App\Controller\NewsController::addNews

news_edit:
    path: /news/{id}/edit
    controller: App\Controller\NewsController::edit

news:
    path: /news
    controller: App\Controller\NewsController::index